// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhNpLiIsa6zYb2FIF7_QR91OfKep4b10',
    appId: '1:686569559624:web:a1678c1cf65b2d1262aa7d',
    messagingSenderId: '686569559624',
    projectId: 'soundboard-95778',
    authDomain: 'soundboard-95778.firebaseapp.com',
    storageBucket: 'soundboard-95778.firebasestorage.app',
    measurementId: 'G-13749SK7MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AvSGJ-CwFxefmx_moJ4sHQovjtehs6k',
    appId: '1:686569559624:android:2b90d0f0ea1c33ab62aa7d',
    messagingSenderId: '686569559624',
    projectId: 'soundboard-95778',
    storageBucket: 'soundboard-95778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8cYGe8I30M4osw-EsTcowRMmfCK2uw-Q',
    appId: '1:686569559624:ios:a04189491866acac62aa7d',
    messagingSenderId: '686569559624',
    projectId: 'soundboard-95778',
    storageBucket: 'soundboard-95778.firebasestorage.app',
    iosBundleId: 'com.example.soundboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8cYGe8I30M4osw-EsTcowRMmfCK2uw-Q',
    appId: '1:686569559624:ios:a04189491866acac62aa7d',
    messagingSenderId: '686569559624',
    projectId: 'soundboard-95778',
    storageBucket: 'soundboard-95778.firebasestorage.app',
    iosBundleId: 'com.example.soundboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhhNpLiIsa6zYb2FIF7_QR91OfKep4b10',
    appId: '1:686569559624:web:917f7f57294aedca62aa7d',
    messagingSenderId: '686569559624',
    projectId: 'soundboard-95778',
    authDomain: 'soundboard-95778.firebaseapp.com',
    storageBucket: 'soundboard-95778.firebasestorage.app',
    measurementId: 'G-MDKQD699R6',
  );
}
